### ISSUE TITLE
[Feature Request] Convert genre byte codes (including "Winamp Extension" codes 80-191) to string values

### ISSUE THREAD

**Issue by bretttolbert** [dhowden/tag#102]
I'm seeing that with some of my mp3 files, `.Genre()` is returning a byte code in parentheses e.g. `"(175)"` but for other files it returns the string value `"Post-Punk"`, as expected. E.g.

```yaml
    - path: /home/pi/Music/Joy Division/Peel Sessions [1986]/08 The Sound Of Music.mp3
      size: 8775680
      format: ID3v2.3
      title: The Sound Of Music
      artist: Joy Division
      album: Peel Sessions
      genre: (175)
      year: 1986
    - path: /home/pi/Music/The Cure/Kiss Me, Kiss Me, Kiss Me [1987]/The Cure - Just Like Heaven.mp3
      size: 5889881
      format: ID3v2.3
      title: Just Like Heaven
      artist: The Cure
      album: Kiss Me, Kiss Me, Kiss Me
      genre: Post-Punk
      year: 1987
```

Is it possible to make your library always convert these codes to string values per [this page](https://en.wikipedia.org/wiki/List_of_ID3v1_genres#Extension_by_Winamp)? I understand that codes in the range 80-191 are not part of the official ID3 spec but are "Winamp Extension" codes but apparently many of my files have them, unfortunately, and I see that you already support Winamp codes in the 80-147 range.
